# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d811f6e6d545889392f17a273641876e5bbd36f405229371d6504efaccab0b3bc042ef69d63ace2502a700ddc46868c7bf2ce6cce16b35a1ba168076033fc264

test:
  secret_key_base: c4292249b86cc642adf7ce7b43d2c347db471551d052f0799b76b7d8ff5fd40ab34217d53837216f3ee2d86b07701b7c81b7dde5849c3d7e9464feb420b6eccf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
